name: Stores 5 PM

on:
  schedule:
    - cron: '2 22 * * *'

permissions: write-all

jobs:
  fetch_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Save Data
        run: python stores2h.py

      - name: Commit and push artifact
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add stores2h/*
          git commit -m "Update Stores Data"
          git push
